//
// Created by Olaf van den Berg on 21-12-2023.
//

#ifndef BRACKOCALYPSE_ROGUELIKESHEETINDOORTYPE_HPP
#define BRACKOCALYPSE_ROGUELIKESHEETINDOORTYPE_HPP
enum RogueLikeSheetIndoorType {
    WallTopLeft = 'A',
    WallTopMiddle = 'B',
    WallTopRight = 'C',
    WallLeftRight = 'D',
    WallBottomLeft = 'E',
    Floor = 'F',
    WallBottomRight = 'G',
    FloorTopLeft = 'H',
    FloorTopMiddle = 'I',
    FloorTopRight = 'J',
    FloorLeft = 'K',
    FloorRight = 'L',
    FloorBottomRight = 'M',
    FloorBottomMiddle = 'N',
    FloorBottomLeft = 'O',
    Door = 'P',
    WallTopExitTop = 'Q',
    BooksLeft = 'R',
    BooksMiddle = 'S',
    BooksRight = 'T',
    ChairTop = 'U',
    ChairBottom = 'V',
    TableLeft = 'W',
    TableRight = 'X',
    TableMiddle = 'Y',
    Drinks = 'Z',
    MoneyBig = 'a',
    MoneyMedium = 'b',
    Gold = 'c',
    KitchenSink = 'd',
    KitchenCabinet = 'e',
    KitchenCabinetBottles = 'f',
    Pans = 'g',
    Bed = 'h',
    Mirror = 'i',
    Table = 'j',
    Candle = 'k',
    OrangeFloor = 'l',
    OrangeFloorTopLeft = 'm',
    OrangeFloorTopMiddle = 'n',
    OrangeFloorTopRight = 'o',
    OrangeFloorLeft = 'p',
    OrangeFloorRight = 'q',
    OrangeFloorBottomLeft = 'r',
    OrangeFloorBottomMiddle = 's',
    OrangeFloorBottomRight = 't',
    BlueFloor = 'u',
    BlueFloorTopLeft = 'v',
    BlueFloorTopMiddle = 'w',
    BlueFloorTopRight = 'x',
    BlueFloorLeft = 'y',
    BlueFloorRight = 'z',
    BlueFloorBottomLeft = '1',
    BlueFloorBottomMiddle = '2',
    BlueFloorBottomRight = '3',
    PillarBottom = '4',
    PillaarTop = '5',

};
#endif //BRACKOCALYPSE_ROGUELIKESHEETINDOORTYPE_HPP
