//
// Created by SKIKK on 16/11/2023.
//

#ifndef BRACKOCALYPSE_ROGUELIKESHEETTYPES_HPP
#define BRACKOCALYPSE_ROGUELIKESHEETTYPES_HPP

enum RogueLikeSheetType {
    Sand = 'A',
    WaterLeftBottomGrassLarge = 'B',
    WaterLeftTopGrassSmall = 'C',
    WoodPile = 'D',
    BoatRight = 'E',
    RockInWaterBig = 'F',
    Grass = 'G',
    BoatLeft = 'H',
    Campfire = 'I',
    MooringPostLeft = 'J',
    TreeBottom = 'K',
    WaterRightBottomGrassSmall = 'L',
    WaterRightBottomGrassLarge = 'M',
    WaterLeftBottomGrassSmall = 'N',
    TreeTop = 'O',
    WaterLeftGrass = 'P',
    WaterBottomGrass = 'Q',
    TreeStumpWithAxe = 'R',
    Stone = 'S',
    Ground = 'T',
    WaterRightGrass = 'U',
    WaterRightTopGrassSmall = 'V',
    Water = 'W',
    WaterRightTopGrassLarge = 'X',
    WaterTopGrass = 'Y',
    WaterLeftTopGrassLarge = 'Z',
    PeerLeft = 'a',
    PeerMiddle = 'b',
    PeerRight = 'c',
    Empty = 'd',
    RockInWaterSmall = 'e',
    MooringPostRight = 'f',
    TentLeftTop = 'g',
    TentRightTop = 'h',
    TentLeftBottom = 'i',
    TentRightBottom = 'j',
    TreeStump = 'k',
    WallTopLeft = 'l',
    WallTopMiddle = 'm',
    WallTopRight = 'n',
    WallLeftRight = 'o',
    WallBottomLeft = 'p',
    Floor = 'q',
    WallBottomRight = 'r',
    FloorTopLeft = 's',
    FloorTopMiddle = 't',
    FloorTopRight = 'u',
    FloorLeft = 'v',
    FloorRight = 'w',
    FloorBottomRight = 'x',
    FloorBottomMiddle = 'y',
    FloorBottomLeft = 'z',
    Door = '1',
    WallTopExitTop = '2',
    BooksLeft = '3',
    BooksMiddle = '4',
    BooksRight = '5',
    ChairTop = '6',
    ChairBottom = '7',
    TableLeft = '8',
    TableRight = '9',
    TableMiddle = '0',
    Drinks = '!',
    MoneyBig = '@',
    MoneyMedium = '#',
    Gold = '$',
    KitchenSink = '%',
    KitchenCabinet = '^',
    KitchenCabinetBottles = '&',
    Pans = '*',
    Bed = '(',
    Mirror = ')',
    Table = '-',
    Candle = '_',

};


#endif //BRACKOCALYPSE_ROGUELIKESHEETTYPES_HPP
