//
// Created by Stef van Stipdonk on 21/12/2023.
//

#ifndef SCENETYPE_HPP
#define SCENETYPE_HPP

enum SceneType {
    HOME_SCENE,
    INTRODUCTION_SCENE,
    FIRST_LEVEL,
    INTERLUDE_ONE_SCENE,
    SECOND_LEVEL,
    INTERLUDE_TWO_SCENE,
    INTERLUDE_THREE_SCENE,
    BOSS_LEVEL,
    END_SCENE
};

#endif //SCENETYPE_HPP
